pipeline {
    agent any

    def pomVersion = ""

    stages {
        stage('Build') {
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
                readMavenPom file: 'pom.xml'
                pomVersion = pom.version
                stash 'source'
            }
        }

        stage('Docker build') {
            steps {
                unstash 'source'
                sh "docker build . -t netodevel/netodevel-api:${pomVersion}"
            }
        }

        stage('Docker push to registry') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'docker_hub_pat',variable: 'dockerHubPat')]) {
                        sh "docker login -u netodevel -p ${dockerHubPat}"
                        sh "docker push netodevel/netodevel-api:${pomVersion}"
                    }
                }
            }
        }

        stage('Apply Kubernetes files') {
            steps {
                withKubeConfig([credentialsId: 'kind-cluster-config', serverUrl: 'https://127.0.0.1:35433']) {
                  sh 'kubectl apply -f k8s'
                  sh 'kubectl rollout restart deployment netodevel-api'
                }
            }
        }
    }
}
