pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker { image 'maven' }
            }
            steps {
                sh "mvn package -Dmaven.test.skip=true"
            }
        }

        stage('Apply Kubernetes files') {
            steps {
                withKubeConfig([credentialsId: 'kind-cluster-config', serverUrl: 'https://cicd-control-plane:51036']) {
                  sh 'kubectl get nodes'
                }
            }
        }
    }
}
